#+TITLE:
#+OPTIONS: toc:nil num:3 H:4 ^:nil pri:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css"/>

This page was created in 2017 and shortly thereafter abandoned. I wanted to learn how to make a webpage with Emacs and OrgMode. This does work so that suceeded. I am going to change this shortly into something else that is a directory for the subdomains. This domain is just my last name and I have email addresses setup as well.

The following is my current gameplan for bjj. This is mostly based on notes I have made from BJJ classes and outside sources. My idea is to actually take the lessons I learn and videos I watch seriously and drill those specific techniques instead of just collecting and forgetting move after move.

I use the term OP and OPs for opponent for shorthand. I am not sure if my notes make sense to anyone but me, but you are free to use what you find useful.

This page is written in [[https://www.gnu.org/software/emacs/][GNU Emacs]] and [[http://orgmode.org/][Org-Mode]] and it is a way to combine two of my hobbies/obsessions. The html for this site is auto generated as I update my notes. This site is hosted on github and these files can be downloaded from [[https://github.com/bcronmiller/][my github page]].

#+TOC: headlines 2

* Guard
** Top Guard
***** Open Guard
****** [[https://www.youtube.com/watch?v=APzRFmKyIhQ][Passing Open Guard -josh robinson]]

In this link from Ronin Submissions Josh Robinson, Josh explains how to establish a good position from open guard before allowing the opponent to control your hips or sleeves. Step one is to establish a knee ride on the thigh of the opponent and allow the knee shield. This immobilizes the hips and stops inversions. Step two is to connect your hands and arms under the thighs and pass to one side or the other.
***** Closed Guard Passing
****** [[https://www.youtube.com/watch?v=DZL7pmQjmyU&list=PLLvUtPaoHJDIXWuF18ZKOC-HNdNhuMqks&index=2][Basic Guard Passing System (VanGuard Gym Coach Doug)]]
******* Basic Guard Break (Guard Break)
******** Double Meathead Pass
After the Basic Guard break you have moved away from OPs hips. This allows OP to put his feet on your hips and create space and control.
The Double Meathead Pass answers this problem. Your arms pummel under the OPs legs and you connect your hands in front of his hips.
This pops OPs feet off of your hips.
Next, pull OP up on your lap to isoloate OPs hips. Grab the far side lapel in the direction you want to pass.
Stand up and drive into the legs as you walk around to the side.
Drive your shoulder into the legs with good posture to pass.
The far side lapel grip will prevent the OP from rolling away.

Note: Doug recommends not grabbing the collar. (This is what I do most times). The collar grab opens you up to the elbow push escape while the lower lapel grip controls the hips better and is not as suseptable to the elbow push because your arm is not as extended.
******** Shoulder in Belly Pass (Over/Under pass)
From the break, You grab one pant grip at OPs knee and the other arm underhooks the leg.
Keep both grips while you drop your shoulder into OPs missection and walk around the guard.
After your knee is established on the hip you are cleared to move the knee grip to a crossface control of the neck.
After that is established you can release the underhook of the leg to secure side control.
Note: You are on your toes and not your knees during this pass
******* Violator/Combat Knee Break
From closed guard establish double bicep control on the OPs closed guard. Stand up and stack the OPs guard.
While standing adjust your feet so that your knee is lined up on OPs centerline.
Sit back into a combat base (forward leg knee up, back knee down)
This will break the guard open and leave you in a good base situation.
Depending on which way OPs shirmps or what side he leans to we will use either Knee Thru or Knee Slice Pass
******** Knee Thru Pass
Knee Thru means that we staple our knee over the OPs thigh on the same side (Right to Right, Left to Left)
1. As OP shrimps we staple the leg with our forward knee
2. At the same time, we reach for a crossface control of the neck and underhook OPs farside leg
3. Pin your knee to control the near side hip
4. Backstep with strong shoulder pressure and a deep crossface grabbing the back of the gi
4a. Extend your hips into the armpit to dominate the side
5. Replace your knee on the hip with your top side hand
6. Switch your knee from the hip to the armpit while pressing OPs face away with shoulder pressure.
******** Cross Knee Pass (Knee Slice Pass)
Cross Knee means we are going from Right to Left or Left to Right with the knee across OPs hips. The key to this pass is to get the underhook on the same side as our knee is coming from to avoid a backtake.
1. As OP shrimps we staple across to the opposite side of our knee.
2. Underhook the far side armpit while pulling up on the near side sleeve
3. Step around OPs bottom leg as you baseball slide into the pass with full pressure on your OP.
4. End at [[*Top][Scarf Control Top]
******** Turk Pass (Leg Weave)
From OPs scissor guard (open guard with a setup for a scissor sweep, knee sheild top leg with a bottom leg outside my legs.
1. Weave your arm under the knee of the knee shield and grip on top of OPs bottom knee.
2. Get to your feet and stack into OP
3. Press forehead and shoulders down and forward to collapse OPs legs together
4. As you press your shoulder into OP, spring up and hop around the legs.
This kills OPs hips and limit his movement
5. Turn the leg weave hand the other way to make room at OPs hips
6. Place your bottom knee into the hip and finish the pass.
7. If OP gets the top knee in between before you finish the pass. Use the leg weave hand to cup the top knee fast and pull it away while you replace your knee and finish the pass.
8. If OPs legs are preventing the pass, keep the same grips and hop to the back side to finish the pass.
** Bottom Guard
***** Overhook Guard game
****** Vale Tudo Guard
******* [[https://www.youtube.com/watch?v=CGDdWRRtGDw][Vale Tudo Guard Vale Tudo Guard -josh robinson]] (similar to my overhook game with a better setup)

Josh explains that you would use your wrists connecting to the back of the neck to break posture instead of pulling collars. I like this because I am getting spiderguard fingers from pulling lapels so if I can be less dependant on those grips it will be better for my hands. I will be able to use my grips for chokes instead of breaking posture as well. It also has the benefit of being able to translate to a no-gi game.

******* [[https://www.youtube.com/watch?v=1t_0crasE_4][Vale Tudo Guard no-gi -josh robinson]] (setup triangle, gogoplata and straight jacket)

In this video Josh explains how to setup the Vale Tudo guard (from the hip instead of being flat on the back). Bicep control is better than wrist control. Feet on hips can be exchanged for a formal closed guard. The overhook keeps the posture broken with a collar tie at times. "Clear the head" means we get the forearm to the overhook side and the foot comes in front for a gogoplata. The triange is available because you are on your hip. The straightjacket submission follows the gogoplata setup when the arm defends the choke. The far arm is pulled through to increase pressure on the choke. This is similar to the collar choke with the far arm pulled across to allow the shoulder to finish the choke. This also leads to an omaplata choke.
******* [[https://www.youtube.com/watch?v=X8Qhl-jmeNs][Closed Guard Arm-drag (Roger Gracie Guard Study)]] (Arm-drag with 2 on 1 grip to setup, back-take, armbar or flower sweep)
The guard is closed and you grab the ops sleve at the wrist and elbow. Using a bridge and a foot on the arm side hip, pull the elbow across your centerline to pin it the side. When the elbow is across teh centerline, three options are available depending on what the op does. 1. take the back 2. arm bar (scrambles into triangle, oomaplata etc) 3. sweep (flower sweep shown in the video)
******** Back-Take
The backtake is availble by pushing the arm away from your center line as you crawl to the back. Be careful to not fall too far forward. In the video, Roger uses an underhook on the legs and strong collar control to stay tight to the op. Roger also tries to hand off the sleeve grip to the far side hand from the armpit. This creates a strong "gift-wrap" style grip around the back and it helps the back take.
******** Arm Bar
The op will raise the head to avoid the backtake. Additionally the op will extend thier neck and use head pressue to prevent the backtake. When this happens, it is possible to go for the armbar instead. If the armbar fails be ready to scramble into the sweep, triangle or oomaplata. Before transitioning from the back take to the armbar, it is nessesary to get your hips out to the side. Roger also sets up the armbar with a far side collar grip. This allows him to anchor and helps get the foot in front of the face. It may also be useful if an opportunity for a choke happens. Keep the back take threat alive while setting up the armbar.

When Roger broke Jacare's arm he climbed his legs up into a high guard that covered the far side shoulder before he committed to the armbar. This allowed Jacare less time to react to the armbar before it was secured.
******** Flower-sweep
The control of the arm that comes with the 2 on 1 sleeve grip will deprive op of base on that side. The example of Roger using the flower sweep in this video is the same climbing guard that Roger used to armbar Jacare. The op had nee raised on the same side as the 2 on 1 arm that Roger controlled. While climbing up and threatening the armbar, Roger used the movement to underhook the ops far side leg (opposite of the controlled arm) and swept to mount. This would have worked with a gi grip as well if he could not get the underhook on the leg.
******* [[https://www.youtube.com/watch?v=FP-qEk83DdQ][Cross-side collar grip (Kron Gracie Guard Study) loopchoke, armbar, anklepick]]
***** [[https://www.youtube.com/watch?annotation_id=annotation_263863977&feature=iv&src_vid=8F6meOljv-s&v=tmGqgXnuNBE][Marcelo Garcia elbow push escape (Guard Rete
* Half-Guard
** Top Half
** Bottom Half
*** [[https://youtu.be/X8Qhl-jmeNs?t=8m34s][Half-Guard roll from bottom to top (Roger Gracie Guard Study)]]
**** From Bottom Half-Guard get perpendicular and reverse the position
Roger gets an overhook on the trapped leg side from bottom half-guard. He is on his side with contol of the belt with his top hand and a unknown grip with his bottom hand. He could have the leg or hip. He plants his outside foot and upas hard while pulling up on the belt to get the ops weight foward while Roger gets his body perpendicular. He uses momentum before the upa to load the op and get him moving in the correct direction. Roger also uses the momentum from the upa to swing his outside leg up as he inverts into the roll
* Side Control
** Top Side
*** [[https://www.youtube.com/watch?v=S1NpPbMGJ6I&feature=youtu.be][Rafael Lovato Jr's Kimura Secrets]] (Thanks Phil)              :bottomside:
**** Notes
 From Side Control Top with an Underhook on the far arm
 1. Pin the near arm under your shin by first pushing the arm down
 2. Windshield Wiper your legs to switch to your other leg and begin to move to North/South
 3. Step over and pull OP to his side to setup the North/South position
 4. Keep a strong underhook on the far arm and put weight on the arm
 5. Step over and settle into the North/South
 6. Use a "mouse trap" move to switch the grip for the Kimura and use the grip at the hand so the wrist lock is available. Make sure you use a no thumb "monkey grip". Using thumbs makes is possible to lose the arm. (I like the wrist lock option to help break the grip)
 7. Lean forward to setup the grip break instead of just using your arms. Use the torso turn to break the grip and move the arm instead of using your arms
 8. Move the arm away up and then behind the back to finish the submission.
** Bottom Side
[[https://www.youtube.com/watch?v=8F6meOljv-s&index=1&list=PLLvUtPaoHJDIXWuF18ZKOC-HNdNhuMqks][Side Control system from VanGuard Gym (Coach Doug Esposito)]]
It is easy to defend if you only try to re-guard. You need to have various options for different situations. This system will give you a plan for escapes.

*** Stone Squirrel Posture [[https://www.youtube.com/watch?v=8F6meOljv-s&index=1&list=PLLvUtPaoHJDIXWuF18ZKOC-HNdNhuMqks][VanGuard side contol escape system]]

The stone squirrel posture is a position from bottom side control. Your hands
control the opponents shoulder and your forearms and elbows frame in between
your chest and your opponent's chest. This frame allows you to raise your arms
over your head (trash truck style) to bring your opponent away from your chest.
Putting your forearms on the chest instead of on the neck gives you more
control. When combined with a bridge space is created that can be used in the positions that follow.

**** Re-Guard

From Stone Squirrel, feet close to hips, bridge into op and lift op back with a
frame. At the same time, shrimp to make room and insert a knee to take up the
space you created. Hook behind the leg or under the leg for a butterfly to re-guard
****** Sweep
If you have the overhook control from the guard and the ops posture is broken, you can sweep from guard to mount.
****** Armbar
If you have a stong underhook on the other arm an armbar is available from the guard with your arm and head pinching the elbow of your opponent.
**** Bottom Single Leg to Side Control – Top/Offensive

From Stone Squirrel, frame with your forearms and elbows and bridge. Ensure that
your feet are not all the way into your hips, that space is needed to "hip
heist". Hip Heist means you thread your nearside foot under your far side leg
and turn belly down. At the same time, windshield wiper and pummel your far side arm to
create an underhook

**** Bump and Roll to Side Control – Top/Offensive
With one arm framed on the hip and the other arm under the chest in stone squirrel, lift and upa into the op to make room for your guard. The op is pressing back to flatten you out. Using this momentum, scoot your hips underneath your op with a hip shovel (do not just roll without getting under the op). The frame on the hip is key to making this work.
***** If OP posts on his hand
The posting opens the OP up so that we can try to reguard or move into another transition. We have to drill all of these defenses so we can link one technique to the others in the system.
**** Rainbow Roll to Side Control – Top/Offensive
The crossface from side control gives us an opportnity to trap that arm. If we can get parrell to the OP we can roll to sweep to top side control from that posistion. This happens naturally when OP is going to North South If we feel the bottom arm transerring to 100 kilos that is a cue that OP is going to North/South. Otherwise, we can move ourselves into a North/South posture to get OP "on a line" by changing the angle. Our hand that is not trapping the crossface arm is going over OPs back to grab his belt. We have to shrimp away from OP and put your armpit on OPs shoulder.
*** Armpit/Prayer Posture (APP)
Armpit/Prayer Posture is similar to Stone Squirrel. The farside hand is in the armpit instead of being at the shoulder. This makes it harder to peek your elbow out for the far side underhook but it allows access to the top single leg. HipBump to move farside hand under the armpit.
**** Top Leg Single to Side Control – Top/Offensive
From APP, bump and shrimp to get rid of the crossface and make OP "float" on your forearms by lifting your forearms to fill the space you created with the bump.
**** Elbow Push to Open Guard
**** All Stone Squirrel Escapes
*** Hands in Front Posture
**** Turn Away to Turtle 1 – Bottom/Defensive, sit thru to Turtle 2 – Top Offensive
**** Monkey or Granby Roll to Bottom Guard
*** Inside Arm Down Posture
**** Pant Grab to Guard or Half-Guard – Bottom
**** Jail Break to Butterfly Guard – Bottom
**** Ghost to Turtle 1 – Top/Offensive
*** Submissions from Bottom
**** [[https://www.youtube.com/watch?v=HLcM9pbELHk][no-gi baseballbat and ezekiel from bottom - josh robinson]]
**** Last resort                                                :subs:bottom:
SCHEDULED: <2016-11-26 Sat>
:PROPERTIES:
:CREATED:  [2016-11-26 Sat 17:14]
:END:

You should try for escapes instead of submissions from inferior positions. We cannot assume that every encounter will be 1 on 1 in a controlled environment. Being in top position gives you a better chance to bail out and run if nessesary.

* Scarf
** Top Scarf
**** TODO [[https://www.youtube.com/watch?v=efox3xBLk50][Josh Robinson Side Control flow from Kesa Katame (with underhook)]] (Stopped at 3:56 on notes - pick up from here)
From side control immediately sit through to the underhook Kesa Katame (scarf hold) with or without the underhook
Staying in side control will be met with a lot of squirming so scarf hold is better
***** Modified Kesa Katame (with underhook)
1. Step over the head right away and look for the armpit armbar on the near side arm In order to sit through, post on your far elbow and pull under his near side elbow to get him to turn. This makes your legs light enought to step over the head. The sitthrough and stepover should be a one two punch.
2. Op pushes the leg away
3. Step back while following the arm to setup a modified gift wrap (Big Rich style) apply pressure for a choke. (similar to the arm triangle)
4. From Big Rich gift wrap, place your bottom side arm on the other side of OPs face to setup the straight armbar
5. Setup the wrist lock from here
6. If OP fights that off, follow the wrist to to setup the keylock (americana arm lock) Make sure to step over the shoulder for the americana, do not stay flat.
***** Kesa Katame (judo style without underhook)

** Bottom Scarf

* North/South
** Top NS
** Bottom NS
* Knee on Belly
** Top KOB
** Bottom KOB
* Back
** Top Back
** Bottom Back
* Mount
** Top Mount
** Bottom Mount
* CACC Notes
** From Billy Riley documentary [[https://youtu.be/wqq_LWudBek?t=4m23s][Billy Riley teaches turtle attack]]
From Turtle with a forearm on the ground.
1. Grab the far arm from under the armpit to control that side
2. With the other hand, push OPs head down to the ground
3. Swing your topside leg over the head and pull as you fall to that side
4. Post on the far arm as you fall so you do not flop to your side but you are upright and ready
5. This will roll OP over and you still have the arm
6. This can lead to topside position or a reverse triangle based on having the head and arm trapped.

Later in the same video is a good fireman throw followed through to side control
** TODO Eric Paulson [[https://www.youtube.com/watch?v=Y_B7Wd4LF28&feature=youtu.be][4 Catch Wrestling Moves]]
   Add notes later

* Notes
** Concepts
*** On a line
Coach Doug uses the term On a line in his side control series. This means that the OP is in a position that does not allow him to base on one side. In judo this can be called a dead angle.
*** Hip Heist
*** Stone Squirrel
*** Top Single leg
Closest to your head instead of closest to your hips
*** Bottom Single leg
Closest to your hips instead of your head. You need to hip heist to get this leg.
** Styles
*** [[https://www.jiujitsutimes.com/purple-belt-k-rolling-belt/][How to Roll as a purple belt]] by Eddie Fyvie
**** Crush you opponents: Focus on using heavy weight and really “crushing” on top.
**** Don’t finish anyone: Try to roll in a way where you catch and release submissions. Focus mainly on positions.
**** Don’t give anything: Don’t give an inch to anyone.
**** Keep it playful, but with a purpose: Keep it playful, but adhere to the principles and pick a goal.
**** Float: Don’t hold positions long; hop around and move quickly.
**** Allow bad positions, but with a purpose: Allow bad positions with the purpose of escaping and defending. Find comfort in discomfort.
**** Go for a “marathon round”: Just roll. Roll so long you have to change your attire. Time limits = sport. No time limits = life
**** Trade moves for concepts

You should be utilizing the principles and concepts passed down by our BJJ forefathers from DAY ONE of your training!

However, at the purple belt, it is time to kick your understanding of concepts into high gear.

Imagine it like art; white belt and blue belt are learning how the artists’ tools work. You learn how to draw, paint, sketch, and at the end of blue belt, you have picked your “style” of art. The white belt and blue belt level doesn’t allow much room for personal thought. You need a concrete foundation and must master the artists’ tools!

When you reach purple belt, you have earned the right to start exploring the “abstract”. You should always experiment and stay fascinated by the difficulty!

“You can listen to me now or wait until you are 65.” – Frank Popolizio

You are now freeing yourself from the stress of mastering the basics and can start opening up and allowing the abstract form of rolling to take shape. You should be seeing the “big picture” of jiu-jitsu much more clearly and have blended the hundreds of techniques you know into concepts that allow you to start applying them rapidly. You must see the “blend” of techniques in the various situations.

The figurative samurai sword has been sharpened once you hit black belt. The purple belt has acquired the sword and has the skills, but still needs to smooth out the blade for extreme precision.
** TrumpetDan Brownbelt Series
TrumpetDan is a great teacher and these videos are full of great technical details that need to be mined. I remember watching these videos when I was a whitebelt and this information was mostly above my head. Other things in these vidoes are things I only just realized I learned from this video series. They are just things I have done for the last 4 years.
*** [[https://www.youtube.com/watch?v=GKbphzgo0sc][TD Brownbelt Series Part 1]]
**** Standing Up from guard passing paths
Get a sleeve and lapel grip and stand to pass while keeping the lapel arm stiff.
Push open the guard and point your foot out while pressuring forward with your knee
The other arm leaves the sleeve grip and "hikes" the knee to prevent a foot on my hip.
***** From DLR
****** OP has DLR hook
******* Backstep and pivot forward
When you backsetup you are avoiding the far leg
******* Pivot back to HQ position and get on top of the far foot
This move defeated the far foot on my leg/hip
****  Torendo Pass
Great detail on the torendo/bullfighter pass. If OP sits up when you grab the knees, step the the side and throw the legs down to that side. OP will be shelled to that side making it hard to pass. Hop to the far side that is undefended to take the back or side control.
**** Deep Halfguard passing sequence
1. From deep halfguard, OP has the underhook for the backtake and an underhook on the far leg for the sweep.
2. First, cross your feet and sit on your underhooked foot and sitback.
3. Grab OPs bottom foot to avoid the backtake.
4. Stablize
5. Bring your arm in front to crossface and remove the underhook on your leg. Crossface hard and grab deep.
6. Switch hips and sprawl to a standard half guard
7. Walk across the OPs hips to get to quarter guard
8. To remove the foot from quarter guard... Using head pressure and a crawling hand from the underhook, stretch out OPs posture. When OP is stretched out he cannot keep your foot when you kick it free.
*** [[https://www.youtube.com/watch?v=PJTrJjIV-CM][TD Brownbelt Series Part 2]]
This video is about the open half guard.
The "open half guard" "93 guard" is a halfguard with a foot on your hip and a knee shield.
Dan starts by explaining that he values positions based on how much weight he can put on the opponent. I think this is a great concept.
1. Attack/Distract the leg: Get an ankle lock on the foot by pressing the toes into your torso while getting an RNC grip on the ankle. This can be used as a distraction if it does not work.
2. Pass: Swim the arm in and grab the pants after pushing the knee down. This pinning the OPs heel to his butt is exactly the same as an excape from KOB where you trap the kneeling leg with an underhook grip. This is an underhook on the ankle instead of an overhook. The overhook on the ankle is next and it is used when OP has a sleeve grip.
2a. After the leg is pinned, turn the corner with your front side knee to get a knee into OPs hips.
2b. Grab behind his back with a crossface and backstep. You can pin the leg with your leg.
2c. Walk OP across his hips to finish the pass.
3. Over-underpass: Establish the grip over his leg to grab his belt and break the grip on your sleeve.
3a. Keep your head to the OVER side of the over under to avoid getting stuffed.
3b. Get up on your toes and walk OP to the Over side to limit movement. (This changing his hip position is a key theme) :theme
3c. Raise your leg to escape half guard to side control nad put he leg under OPs legs to keep his hips out of play.

(This is similar to the passing concept that Jason Scully showed me at the Montreal seminar. Finishing the pass with a foot posted and OPs legs hanging off of your leg prevents scrambles)

I had to stop the video [[https://youtu.be/PJTrJjIV-CM?t=6m49s][here]] on 12/3 so I can get to class :)
*** [[https://www.youtube.com/watch?v=UUqH4rb7WBc][TD Brownbelt Series Part 3]]
*** [[https://www.youtube.com/watch?v=3H2gpKUHq10][TD Brownbelt Series Part 4]]
*** [[https://www.youtube.com/watch?v=3qFwa0ZhV2g][TD Brownbelt Series Part 5]]
*** [[https://www.youtube.com/watch?v=sm8NKHFlPNI][TD Brownbelt Series Part 6]]
*** [[https://www.youtube.com/watch?v=MtPki5X7mrU][TD Brownbelt Series Part 7]]
*** [[https://www.youtube.com/watch?v=L19elzK79hw][TD Brownbelt Series Part 8]]
* Class Notes
** Topic taught Passing 93 Guard (halfguard with knee-sheild)         :TOPIC:
   :LOGBOOK:
   CLOCK: [2016-12-04 Sun 19:07]--[2016-12-04 Sun 19:08] =>  0:01
   :END:
 [2016-12-03 Sat 11:07]
 In this class, I took notes and I will type them in later...
** Topic taught Chokes from TopBack/Escape from BottomBack            :TOPIC:
   :LOGBOOK:
   CLOCK: [2016-12-05 Mon 20:47]--[2016-12-05 Mon 21:48] =>  1:01
   :END:
 Chokes from Back - From Back control with over/under keep the bottom hand covering the top. Get a collar grip with the choking hand and use one of the following options for the other hand.
 1. Grab the lower lapel and complete the classic collar choke
 2. Switch to an eziekiel (spelling?) choke by bringing the non-choking hand behind the head and grabbing the sleeve
 3. If you have the collar grip, switch to the leg for the bow and arrow choke
 4. From bow and arrow, switch to moving the arm behind the arm/head to finish the choke
 5. Feed your Gi lapel from under OPs armpit to the choking hand - setup the same bow and arrow choke or under arm finish.

 Escape from Back Control
 1. Turn torward the choking arm and post on your hand to get to turtle
 2. Raise your hips to try to make OP post a hand.
 3. Grab the hand and move push it to the other side of you head
 4. Roll to the side away from OP to get your shoulders on the mat
 5. Grab OPs knee with both hands to prevent the mount and get top position
 6. Underhook the leg while allowing mount to sneak out of the back door (so to speak)

 No rolling today, Just positional sparring from positions

 Drilling:
 Drilled Roger Gracie Guard and Vale Tudo Gaurd together. If I cannot get the Vale Tudo setup I try to drag the arm across for the Roger Gracie setup and that ususally leads to a scramble that allows the Vale Tudo setup. The constant work makes it hard for OP to work on thier game.

 Drilled Stone Squirrel w/Mac
 Worked with light resistance and worked on several options
 Sucessfully framed up into Stone Squirrel by bumping and raising my arms up.
 Try to get my knee in to re-guard
 Roll for the hip heist or high single depending on where OP goes

 I was able to work and chain together some escapes but I did not have heavy resistance

 Drilled DLR pass w/Isaac
 1. Starting from DLR
 2. Get knee grip and lapel grip
 3. Stepback bringing the knee grip with me to turn OP
 4. Turn back in to lose the DLR hook and setup Mission Control
 5. Control "hike" the top leg for control
 6. Swim down to establish a knee ride on the bottom thigh and pressure the top leg
 7. Get a back grip and collar grip
 8. Switch the knee ride from one to the other and post out the far leg
 9. Pin the top leg at the calf with the posted leg
 10. Switch hips to setup the hop to the far side
 11. Hop to the far side and end with KOB or hip
 12. Be ready to switch if OP shrimps

 There is a lot of details but it started to make sense as I worked through some reps. I need to get this practice in every week/day


 [2016-12-05 Mon 20:47]
** Topic taught Passing Scissor Guard with leg weave and pressure     :TOPIC:
  :LOGBOOK:
  CLOCK: [2016-12-07 Wed 22:07]--[2016-12-07 Wed 22:28] =>  0:21
  :END:
*** Steps
 1. Establish the leg weave while pinning the bottom arm with a sleeve grip.
 2. Sprawl and use shoulder pressure to collapse OPs legs together
 3. As you walk around the legs using head pressure, pull the top leg to prevent a hip escape

*** Drilling:
 Drilled the move from the class with resistance. I had trouble clearing the legs and I could not hop to the far side either. I think I needed to move to the leg switch and to pin the leg better.

*** Rolling
 I rolled in a few rounds from guard switching top and bottom. I had an interesting escape from a triangle. I tried to turn into the hips from my trapped arm side but I was not able to get a good angle. I switched to the feet in the armpit sitback escape I was only able to get the untrapped arm side foot in the armpit but the escape worked when I used both legs. When the triangle broke open, I ended up in a pass by keeping my arm that I used to get out of the triangle.

 From guard I was able to pull the arm across to take the back with white belts. I had a harder time getting into Vale Tudo Guard and the Roger Gracie guard setup. I was able to keep my guard and threaten but I think I needed to push harder on my first move to setup my second and third moves. I show the sweep attempt too much before I go for it and I need to get them moving so I will have momentum to use.

 [2016-12-07 Wed 22:07]
** Topic taught Arm drag from closed guard with lapel over arm grip - Julio's class :TOPIC:
   :LOGBOOK:
   CLOCK: [2016-12-12 Mon 20:52]--[2016-12-12 Mon 21:16] =>  0:24
   :END:
 Lesson
 1. From closed guard, open the lapel and get a cross grip over OPs arm with a thumb up grip.
 2. Grab the wrist of the same arm with your same side hand
 3. Bridge and break the grip while straigtening you arm
 4. Pull the arm to the side while using your legs to break his posture to the side
 5. Shrimp out and reach over OPs head and hand yourself the lapel
 Options:
 1. Reach behind the other arm to finish the choke
 2. Underhook the leg to get the flower sweep
 3. Climb the guard high and setup the armbar

 Drilling:
 Drilled Side Control escapes with Kyle. I got reps in with the stone squirrel to guard recovery and to hip heist single leg. When drilling it live I had a real hard time. Kyle would sit through to Kesa with a grip on my shoulder. I would need to switch to the armpit push escape but Kyle would step over my head and work the inverted triangle.
 Kyle showed me a good concept to work that was very helpful. ** I need to work to get a same side sleeve grip. I started drilling with this and it made everything much easier. In order to set up the grip I am gripping the elbow while working the other escapes. If that arm moves I need to double up on that grip and push while I shrimp.
 I was able to get one reversal completed from that position when fighting for the sleeve everything else opened up.

 I drilled the Vale Tudo Guard / RG guard but only one or two reps and today's class was good practice for this same type of work.
 [2016-12-12 Mon 20:52]
** Topic taught Nothing, I was late                                   :TOPIC:
   :LOGBOOK:
 I was stuck at work late and did not get to class until there was only a few minutes left. Julio encouraged me to get changed and he rolled with me for 15-20 minutes. We were working from my guard. Great lessons as usual from rolling with the Master.
 Posture is important - He keeps a good posture to avoid my game.
 Stand in guard and keep your feet pointed outward
 Do not allow grips
 Fight for outside grip control to avoid armbars.

 I was able to pull him forward but before I could do anything with this he was back in balance.

 Keeping the same side sleeve grip and keeping this grip between our hips helps prevent guard passes.

 It was a good night. Even though I missed 90% of the night, I was able to get something out of small amount of time I had available.
   CLOCK: [2016-12-14 Wed 21:57]--[2016-12-14 Wed 22:06] =>  0:09
   :END:
 [2016-12-14 Wed 21:57]
